import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "on-surface": "#191c1d",
        "primary-container": "#141b2b",
        "on-primary": "#ffffff",
        "primary-fixed": "#dce2f7",
        "secondary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "muted-text": "#6B7280",
        surface: "#f8f9fa",
        "glass-fill": "rgba(255, 255, 255, 0.7)",
        "tertiary-container": "#00201c",
        "on-primary-fixed": "#141b2b",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#404758",
        "secondary-container": "#6063ee",
        "tertiary-fixed-dim": "#4fdbc8",
        background: "#f8f9fa",
        "on-primary-container": "#7d8497",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#009485",
        "on-tertiary-fixed": "#00201c",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "tertiary-fixed": "#71f8e4",
        "inverse-primary": "#c0c6db",
        tertiary: "#000000",
        primary: "#000000",
        secondary: "#4648d4",
        error: "#ba1a1a",
        "surface-dim": "#d9dadb",
        outline: "#76777d",
        "on-surface-variant": "#45464c",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8e9",
        "outline-variant": "#c6c6cd",
        "glass-stroke": "rgba(255, 255, 255, 0.4)",
        "on-background": "#191c1d",
        "surface-tint": "#575e70",
        "inverse-on-surface": "#f0f1f2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        "margin-mobile": "20px",
        gutter: "24px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "margin-tablet": "40px",
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        button: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "72px",
          { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        button: ["15px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
